In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_notes = [[1,3,4],[2,4,3],[2,3,3]]

In [6]:
np.array(my_notes)

array([[1, 3, 4],
       [2, 4, 3],
       [2, 3, 3]])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.arange(2,32,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [12]:
np.linspace(2,33,7)

array([ 2.        ,  7.16666667, 12.33333333, 17.5       , 22.66666667,
       27.83333333, 33.        ])

In [13]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(3)

array([0.72481139, 0.554642  , 0.25028275])

In [15]:
np.random.rand(3,2)

array([[0.56693296, 0.86031664],
       [0.43690413, 0.34640312],
       [0.01624563, 0.81824831]])

In [16]:
np.random.randint(3,20,4)

array([15,  5, 12,  5])

In [20]:
x = np.arange(22)

In [21]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [22]:
x.reshape(2,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [23]:
x.max()

21

In [24]:
x.min()

0

In [26]:
x.argmax()

21

In [27]:
#siguiente clase

In [28]:
new_list= np.arange(0,12)

In [29]:
new_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
new_list[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
new_list[2:4]

array([2, 3])

In [32]:
#recuerda el index

In [33]:
new_list < 8

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False])

In [34]:
neww = np.arange(0,50).reshape(5,10)

In [35]:
neww

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
neww[3:4,3:5]

array([[33, 34]])

In [42]:
neww[4:7,7:9]

array([[47, 48]])

In [43]:
#NUMPY OPERATIONS

In [44]:
neww - 20

array([[-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [45]:
neww / neww

C:\Users\Diego\AppData\Local\Temp\ipykernel_8756\1469307956.py:1: RuntimeWarning: invalid value encountered in divide
  neww / neww


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [46]:
neww ** neww

array([[          1,           1,           4,          27,         256,
               3125,       46656,      823543,    16777216,   387420489],
       [ 1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
         1500973039,           0,  1681328401,   457441280,  -306639989],
       [          0,   878082373,   977272832, -1276351769,           0,
         1296002393,   603979776,  -714244925,           0, -1266004979],
       [ 1073741824, -2010103841,           0,   942687265,           0,
          618402555,           0,  -200711083,           0,  1583713495],
       [          0,  2110296937,           0,   407106611,           0,
        -1714755555,           0,  1686099919,           0,    20963633]])